name = "Lmao"
version = "0.1.0"
defaultTargets = ["lmao"]

[[lean_lib]]
name = "Lmao"

[[lean_lib]]
name = "Demo"

[[lean_exe]]
name = "lmao"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"
